Traceback (most recent call last):
  File "C:/Users/user/PycharmProjects/chapter8/errorexample.py", line 15, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
